//var url="http://192.168.1.100:8080/hhdj";
var url="http://211.67.177.56:8080/hhdj";
export default {
  Server:url,
  News:`${url}/news/newsList.do`,
  Newsdetail:`${url}/news/newsContent.do`,
  Mien:`${url}/party/partyList.do`,
  Interaction:`${url}/forum/forumList.do`,
  fileList:`${url}/studyFile/fileList.do`,
  login:`${url}/user/userLogin.do`,
  userInfo:`${url}/user/userInfo.do`,
  updateInfo:`${url}/user/modifyInfo.do`,
  uppass:`${url}/user/updatePwd.do`,
  thought:`${url}/report/addReport.do`,
  summary:`${url}/impress/saveImpress.do`,
  branchList:`${url}/branch/findAll.do`,
  Comment:`${url}/nationComment/getComment.do`,
  judgeComment:`${url}/nationComment/judgeComment.do`,
  submitSummary:`${url}/nationComment/submitSummary.do`,
  updateBranch:`${url}/nationComment/updateBranch.do`,
  ParticipatingMembers:`${url}/nationComment/userList.do`,
  isComment: `${url}/nationComment/isComment.do`,
  userSummary:`${url}/nationComment/userSummary.do`,
  submitComment :`${url}/nationComment/submitComment.do`,
  integralList:`${url}/integral/integralList.do`,
  Qiniu_UploadUrl:`${url}/image/uploadBase64.do`,
  reportInfo:`${url}/report/reportInfo.do`,
  checkByUserId:`${url}/impress/checkByUserId.do`,
  forumDetail:`${url}/forum/forumDetail.do`,
  forumCommentList:`${url}/forum/forumCommentList.do`,
  addComment:`${url}/forum/addComment.do`,
  findBranchNameById:`${url}/branch/findBranchName.do`,
  saveForum:`${url}/forum/saveForum.do`,
  carousel:`${url}/carousel/carouselList.do`,
  proxy:`${url}/proxy/proxy.do`,
  systemError:`${url}/exception/catch.do`,
  newsType:['信工新闻眼','特色活动','通知早知道','党建一点通','制度建设','党员亮身份','随时随地学','随时随地拍','政治学习']
}

